backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "people"
    label: "People"
    folder: "src/pages/people"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "person"}
      - {label: Name, name: name, widget: string}
      - {label: Profile Picture, name: image, widget: image}
      - {label: Bio, name: bio, widget: string}
      - {label: Email, name: email, widget: string, required: false}
      - {label: Website, name: website, widget: string, required: false}
      - {label: Twitter, name: twitter, widget: string, required: false}
      - {label: Github, name: github, widget: string, required: false}
      - {label: LinkedIn, name: linkedin, widget: string, required: false}
  - name: "article"
    label: "Article"
    folder: "src/pages/articles"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author Name", name: "author", widget: "string"}
      - {label: "Author Twitter", name: "twitter", widget: "string", required: false}
      - {label: "Author LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Author Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "SEO Description", name: "description", widget: "text"}
  - name: "webinar"
    label: "Webinars"
    folder: "src/pages/webinars"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "webinar"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Speaker Name", name: "speaker", widget: "string"}
      - {label: "Speaker Twitter", name: "twitter", widget: "string", required: false}
      - {label: "Speaker LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Speaker Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Author Name", name: "author", widget: "string"}
      - {label: "Author Twitter", name: "twitter", widget: "string", required: false}
      - {label: "Author LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Author Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "SEO Description", name: "description", widget: "text"}
  - name: "course"
    label: "Courses"
    folder: "src/pages/courses"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "course"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Length", name: "length", widget: "string"}
      - {label: "Delivery", name: "delivery", widget: "string"}
      - {label: "Course Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Overview", name: "body", widget: "markdown"}
      - {label: "SEO Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Instructors"
        name: "instructors"
        widget: "list"
        fields:
          - label: Instructor
            name: person
            allow_add: true
            widget: object
            fields:
              - {label: Name, name: name, widget: string, default: "Kevin Griffin"}
              - {label: Image, name: image, widget: image}
              - {label: Bio, name: bio, widget: string}
              - {label: Email, name: email, widget: string, required: false}
              - {label: Website, name: website, widget: string, required: false}
              - {label: Twitter, name: twitter, widget: string, required: false}
              - {label: Github, name: github, widget: string, required: false}
              - {label: LinkedIn, name: linkedin, widget: string, required: false}
      - label: "Course Objectives"
        name: "objectives"
        widget: "object"
        fields:
          - label: "Objective"
            name: objective
            widget: list
            allow_add: true
            fields:
              - {label: "Objective Name", name: value, widget: string}
      - label: "Course Outline"
        name: "outline"
        widget: "object"
        fields:
          - label: Task
            name: task
            widget: list
            allow_add: true
            fields:
              - {label: "Task Name", name: value, widget: string}
              - label: Sub-Task
                name: sub_task
                widget: list
                allow_add: true
                fields:
                - {label: "Sub-Task Name", name: value, widget: string}
      - label: "Prerequisites"
        name: "prerequisites"
        widget: "object"
        fields:
          - label: "Prerequisite"
            name: prerequisite
            widget: list
            allow_add: true
            fields:
              - {label: "Prerequisite Name", name: value, widget: string}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
